name: Create binary installers
on:
  push:
    branches:
      - 'main'
  pull_request:
    branches:
      - 'main'

jobs:
  pip-compile:
    strategy:
      fail-fast: false
      matrix:
        output-file:
          - darwin-x86_64-reqs
          - linux-x86_64-cuda-reqs
          - windows-x86_64-cuda-reqs
        python-version:
          # - '3.9'
          - '3.10'
        include:
          - output-file: darwin-x86_64-reqs
            os: macos-12
          - output-file: linux-x86_64-cuda-reqs
            os: ubuntu-22.04
          - output-file: windows-x86_64-cuda-reqs
            os: windows-2022
    name: py${{ matrix.python-version }}-${{ matrix.output-file }}
    env:
      output-file-name: py${{ matrix.python-version }}-${{ matrix.output-file }}
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout sources
        id: checkout-sources
        uses: actions/checkout@v3

      - name: setup python
        id: setup-python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      - name: install pip-tools
        id: install-pip-tools
        run: pip3 install pip-tools

      - name: debug output
        run: |
          pip3 -V
          python3 -V
          pip3 list

      - name: run pip-compile
        id: pip-compile
        run: pip-compile -r --annotate --annotation-style split --generate-hashes --emit-index-url --allow-unsafe --resolver=backtracking --reuse-hashes --output-file=binary_installer/${{ env.output-file-name }}.txt binary_installer/requirements.in

      - name: Archive results
        id: archive-results
        uses: actions/upload-artifact@v3
        with:
          name: results_${{ env.output-file-name }}
          path: binary_installer
